# Database Configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ls-0b9a6149e457b534c627b7068f91d8f91e9e8141.cordd8kaddx0.ap-northeast-2.rds.amazonaws.com:3306/chatez
    username: dbmasteruser
    password: chatez-1234

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  # Thymeleaf Configuration
  thymeleaf:
    cache: false


